### ISSUE TITLE
Stone Portal doesn't allow metals.

### ISSUE THREAD

**Issue by eviltek2099** [blaxxun-boop/TargetPortal#40]
Using mod with default settings on ashlands PTS Stone portals do not allow any metals to pass.

**Comment by blaxxun-boop** [comment]
Do not play modded on the PTB, do not report issues from the PTB. Thanks

**Comment by eviltek2099** [comment]
I guess you don't want to get ahead of things, your loss

**Comment by blaxxun-boop** [comment]
Iron Gate asks everyone, to not play modded on the PTB. It just causes more work for both, the Valheim devs and the mod authors, since people report mod bugs to the Valheim devs and vanilla bugs to the mod authors. And then there are bugs that are intertwined, weird vanilla behaviour paired with weird mod behaviour.

The PTB is meant to test vanilla for bugs, so they can get fixed quickly and the update can be release quickly.
Mod authors are responsible for testing their mods on the PTB, not the players. Please do not play modded on the PTB. Thanks.

**Comment by eviltek2099** [comment]
So just to be clear, I was testing your mod to make sure that it worked before starting our communities play through when it reaches EA. I would not report bugs till Iron Gate, when using mods. That's just silly. I was reporting it to you to ensure that when it does reach EA, that any issues would be solved. I don't want to start using a mod only to find out that towards the end of the game, it doesn't work right and have to remove it. Can you confirm that on or nearly after release to EA, that this mod will work with stone portals? If not, I will be forced not to use this mod for our play through with our community.
