### ISSUE TITLE
Lock a portal group to only owner being able to change?

### ISSUE THREAD

**Issue by Sketaful** [blaxxun-boop/TargetPortal#45]
Is there a possibility to add that the portal can be locked from being changed by anyone but the "owner"?

As it is now. Anyone changing the group from open, private, guild etc becomes the owner. 
The problem is that if anyone want to make a portal usable by everyone then it only needs one bad player to go there and make it private or something.

Also, would it be possible to somehow support cross server mods for portals, any of them? Any kind of support. Turning of this mod for like stone portals and just use them would work. anything to make it possible.

**Comment by blaxxun-boop** [comment]
No, because everyone can simply destroy and rebuild the portal anyway. And if you use WardIsLove to prevent that, then WardIsLove will also prevent other people from changing the portal mode.

Portals to other servers are on my to-do list, but it's not that easy to make it work with ServerCharacters.

**Comment by Sketaful** [comment]
Oh Ok. My main problem with it is that people change it by misstake.
