### ISSUE TITLE
New portals not (always) usable by everyone

### ISSUE THREAD

**Issue by Daemonias** [blaxxun-boop/TargetPortal#48]
We're playing on a locally hosted server with 4 players.
We're all running the newest version of Valheim and the newest version of the mod (2024-6-17 | 1.1.20)

### Abbreviations:
- Portal Built by Someone Else = PBSE
- Player that hasn't built the portal = No Portal Builder = NPB
- Portals built by the admin = PBA

### Problems:
When someone builds a portal the other people can't see it
Sometimes that's not true but we haven't found out any hard rules yet, following some variants.

1. Sometimes the PBSEs are usable after a NPB has seen them personally
2. Sometimes the PBSEs are only usable after a NPB has rebooted the game
3. Sometimes only PBAs are not usable immediately by NPBs
4. Sometimes PBSEs are immediately usable by everyone

We haven't tracked the variants to the game version, but they're all with the same modversion.
Yesterday 1. and 2. were true.

**Comment by blaxxun-boop** [comment]
Means you have a mod messing up data transfer. A common culprit for this would be better networking.

**Comment by Daemonias** [comment]
I don't know which of our mods could do that..

1. denikson-BepInExPack_Valheim-5.4.2202
2. Smoothbrain-TargetPortal-1.1.20
3. ValheimModding-Jotunn-2.20.3
4. ValheimModding-HookGenPatcher-0.0.4
5. MSchmoecker-MultiUserChest-0.5.10
6. Advize-PlantEasily-1.8.1
7. Azumatt-AzuClock-1.0.3
8. Azumatt-AzuAutoStore-3.0.3
9. Xenofell-TorchesEternal-0.2.0
10. Azumatt-AzuCraftyBoxes-1.5.3
11. Azumatt-AzuExtendedPlayerInventory-1.4.3
12. CookieMilk-CarryMeMaster-1.0.1
13. blacks7ar-WeaponHolsterOverhaul-1.1.7

Those are the ones we have loaded atm

**Comment by Daemonias** [comment]
> Means you have a mod messing up data transfer. A common culprit for this would be better networking.

Can you please take another look at this issue? @blaxxun-boop 

I don't think it's a network issue since to my knowledge none of my mods have a network component

**Comment by martindemharter** [comment]
Hi. I once had similar problems. 

Sounds like the installation of the mod on server is broken / not installed. Try to (re-) install it. 

Because this portal mod needs its server component. The server component is to share portals between players outside render distance. It won't work without the mod on serverside, you only "see" portals, that are in render distance or have been found within the same game session. 

Another hint: It is not possible, to have both portals running within the same game.

**Comment by Daemonias** [comment]
> Hi. I once had similar problems.
> 
> Sounds like the installation of the mod on server is broken / not installed. Try to (re-) install it.
> 
> Because this portal mod needs its server component. The server component is to share portals between players outside render distance. It won't work without the mod on serverside, you only "see" portals, that are in render distance or have been found within the same game session.
> 
> Another hint: It is not possible, to have both portals running within the same game.

I understand what you're writing.
I don't understand how to make use of it.
Are you saying that ONLY the hosting player should have the mod installed? We're NOT playing on a dedicated Server but one player has the server file and it's running through him and as of now we have it so that everyone is running the same mods... regardless of if they're players OR the admin

**Comment by ShiroMBY** [comment]
> 

You haven't solved your problem?

**Comment by Daemonias** [comment]
> > 
> 
> You haven't solved your problem?

Nope.
It's still persisting. But I haven't played yet since the new patch went live.
Maybe it's better now, maybe a new host of problems have crept up.

**Comment by Daemonias** [comment]
@martindemharter Can you elaborate in regards to your solution proposal?

**Comment by martindemharter** [comment]
Hi. Sure, will do. 

For this mod to work properly, you need to install the same mod files on any participating client no matter the specific role (dedicated server, game or regular client) of the game. 

Basically everyone who starts valheim.exe (so also the server instance) needs this mod in the current version. It seems that it is not the case because your "not always" working sounds exactly like when you have loaded the gate within the current play session and thats why you can use it. 

So probably at least one participant hoster or client does not have it working. For example logging off and on again resets this stuff, because the map progress ist stored serverside. 

side note: 
Mods do not always work properly if you are on beta channel in steam. Always use official public early access branch.
